name: run job for every 10minutes

on:
  schedule:
    
    - cron: '*/50 * * * *'
  
jobs:
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: runs every 50min
        run: echo "This step will always run for 50min"
 
