name: run job for every 10minutes

on:
  schedule:
    
    - cron: '*/10 * * * *'
  
jobs:
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: runs every 10min
      - run: echo "This step will always run for 10min"
 
  
